### PR TITLE
Cocoapods support

### PR DESCRIPTION
**Pull request by joeboyscout04**
Hey there, 

Was looking for exactly this tool for my project, but I like to only use Cocoapods for dependencies.  So I made this into a Cocoapod.  It's my first time doing a Cocoapod so it's not quite "production ready" and the example project doesn't work, but it's a start.  I'm using it as a pod in one of my other projects. 

Be aware I did make several breaking changes to the AssetChecker.swift file, including renaming it and refactoring it some. We can continue to iterate on it if you want.

### CODE REVIEW

**Comment by joeboyscout04** [comment]
Be aware I did make several breaking changes to the AssetChecker.swift file, including renaming it and refactoring it some.  We can continue to iterate on it if you want.

**Comment by s4cha** [comment]
Hi @joeboyscout04 
Thanks a ton for your great work,
I didn't even know we could distribute scripts through Cocoapods, I'm going to to look how you did it.
An Example Project is a very good idea as well, we have one for https://github.com/freshOS/Localize but haven't added one for AssetChecker so it's a very welcome addition.
I'm going to try review this today.

Thanks a ton for you time and effort :)

**Comment by joeboyscout04** [comment]
Yeah probably it's a bit overkill to add just a script through cocoapods, but I prefer to have the dependency management.  Plus if you add additional functionality (detecting unused font files, for example), then maybe you want more than just one script.

**Comment by s4cha** [comment]
@joeboyscout04 this is plain fantastic :)
Please excuse the time I took to review this, it was a busy end of the year.

Since you've spent a lot of time and effort making AssetChecker better, and as a sign of trust, we invited you to the freshos team. Welcome !
On top of that I just gave you write access to AssetChecker repo so it's more convenient for you to make PR's.

Have a fantastic 2018 🍾 !

**Pull request merged**
